FROM httpd:2.4
#here  " . " >> it will comy all from this directory , "/usr/local/apache2/htdocs/" >> the destenation 
COPY . /usr/local/apache2/htdocs/

#docker build . -t myweb:1
#docker run -p 8080:80 myweb:1
#got to chorme and got to localhost:8080 >> result shouild be Hello from docker 
#to close the container from terminal u sholud press control + C
