#First Challenge
#Use Alpine Linux base image
#Run: echo "Hello from Alpine"
#Build the image called: myalpineimg with a tag of: 2020
#Run a container with your image

FROM alpine:latest
CMD echo "Hello from Alpine!"


#steps 
#1- go to directory :cd FirestChallenge 
#2- docker build . -t myalpineimg:2020
#3- docker run myalpineimg:2020
