FROM httpd:2.4
#here  " website.tar.gz " >> it will copy this file from this directory , "/usr/local/apache2/htdocs/" >> the destenation 
ADD website.tar.gz /usr/local/apache2/htdocs/

#cd CVA
#docker build . -t myweb:2
#docker run -p 8080:80 myweb:2
#got to chorme and got to localhost:8080 >> result shouild be Hello from tar file 
#to close the container from terminal u sholud press control + C
