FROM nginx:latest

CMD echo "Hello World!"

#we try to build an image to return word "Hellow world"  
#after write code we run  
#docker build . -t myfirstimage:1 
#docker run myfirstimage:1 
#result should be  "Hello World!"
